title = "HannesBräu"
#baseURL = "https://www.hannesbru.de/"
#baseURL = "C:/Hugo/Sites/hb_anake/public"
#baseURL = "/media/data/Code/projects/hannesbraeu/hb_website/public"
#baseURL = "//homeserver.local/server_ext_disks/Code/projects/hannesbraeu/hb_website/public"
#baseURL = "https://vibrant-mirzakhani-375433.netlify.app/"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
#themesDir = "/themes"
relativeURLs = true
uglyURLs = false
absURL = true

MetaDataFormat = "yaml"
DefaultContentLanguage = "de"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-136382051-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Website HannesBräu"
  #site_logo = "images/main/logo.png"
  instagram = "https://www.instagram.com/hannesbraeu/"
  facebook = "https://www.facebook.com/HannesBr%C3%A4u-113490456706196/?view_public_for=113490456706196/"
  #twitter = "https://twitter.com/brau_hannes"
  google = "https://g.page/hbverne?share"
  shop = "https://hannesbraeu.sumup.link/"
  merch = "https://hannesbrau.myspreadshop.de/"
  #youtube = ""
  #github = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  #featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
  custom_css = ["css/main.css"]
  body_classes = "avenir bg-near-white"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
